### PR TITLE
code changes to work with latest caffe

### PR DESCRIPTION
**Pull request by Sravan2j**
I removed switch case, so I ended up doing code alignment. Probably because of this alignment, you may find different number of line changes.

Also I changed the logic for "InnerProduct" both in convertProtoToLua() and loadModule(). Please let me know if I need to do any changes to it.

### CODE REVIEW

**Comment by szagoruyko** [comment]
Good job! the models in caffe model zoo are in old format and it's not good to break their support. Can you add a second branch v1 with the old code?

**Comment by Sravan2j** [comment]
@szagoruyko, Yes, I added a branch "v1" with the old code (until the commit "removed global module list") in my repository. I think your recent commit i.e., "update to support the update caffe binding" should be added to the new code. Will you do those changes? or do I need to pull your changes into my branch and rebase it?

Please let me know. Thanks for your time.

**Comment by szagoruyko** [comment]
sorry I wasn't clear, by branch I meant an if statement which goes to V1 for old caffe or V2 for new. I can do that myself next week.

**Comment by Sravan2j** [comment]
Oops! Sorry for misunderstanding. I did those changes. But some clean up is needed in the code. I will push the changes once I am done with cleanup.

-----Original Message-----

**Comment by Sravan2j** [comment]
@szagoruyko, I updated code to compatible with caffe v1. Please check the code and let me know if any other changes are required.

**Comment by szagoruyko** [comment]
Supercool! Thanks a lot!

**Pull request merged**
