### PR TITLE
port to windows with msvc

### PR DESCRIPTION
**Pull request by BTNC**
Hi,

This change is to get loadcaffe compile with msvc and work on windows.

Thanks,

### CODE REVIEW

**Comment by MrZoidberg** [comment]
any plans to merge?

**Comment by szagoruyko** [comment]
Awesome, thanks! sorry haven't seen the PR

**Comment by MrZoidberg** [comment]
thanks @szagoruyko @BTNC. Still doesn't work 'cause it cannot find protobuf packages ` Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)`. How can I install them on Windows since there is only protoc.exe for Windows?

**Comment by BTNC** [comment]
conda install -n torch-vc14 -c conda-forge protobuf
Replace torch-vc14 to your conda environment name if it is not your case.

**Pull request merged**
